{
	"version": 1594741391,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sprite5-sheet0.png",
		"images/joinha-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite28-sheet0.png",
		"images/sprite29-sheet0.png",
		"images/brilhodosol-sheet0.png",
		"images/tiledbackground6.png",
		"images/sprite33-sheet0.png",
		"images/sprite30-sheet0.png",
		"images/sprite30-sheet1.png",
		"images/sprite31-sheet0.png",
		"images/sprite31-sheet1.png",
		"images/bola_brasil-sheet0.png",
		"images/sprite34-sheet0.png",
		"images/particles.png",
		"images/sprite-sheet0.png",
		"images/band_gol_alem-sheet0.png",
		"images/band_gol_alem-sheet1.png",
		"images/sprite3-sheet0.png",
		"images/sprite3-sheet1.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"media/goal.ogg",
		"media/som de apito audio (mp3cut.net).ogg",
		"media/interface1.m4a",
		"media/interface1.ogg",
		"media/interface6.m4a",
		"media/interface6.ogg",
		"media/robot arm moving-soundbible.com-503911197 (mp3cut.net).m4a",
		"media/robot arm moving-soundbible.com-503911197 (mp3cut.net).ogg",
		"media/large industrial robot-soundbible.com-1509415522 (mp3cut.net).m4a",
		"media/large industrial robot-soundbible.com-1509415522 (mp3cut.net).ogg",
		"media/soccer stadium sound effect.ogg",
		"media/system of a down.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}